In [1]:
import scipy.io
from scipy.io import loadmat
from scipy.io import savemat
import numpy as np
import pandas as pd

In [7]:
def combine_mat_files(file1_path, file2_path,file3_path, output_file):

    # Load data from the first file
    mat_data1 = scipy.io.loadmat(file1_path)
    array1 = mat_data1['all_features']  

    # Load data from the second file
    mat_data2 = scipy.io.loadmat(file2_path)
    array2 = mat_data2['all_features']  

    mat_data3 = scipy.io.loadmat(file3_path)
    array3 = mat_data3['all_features']  

    # Combine the two arrays into a single row
    combined_array = np.concatenate((array1, array2,array3), axis=1)
    print(combined_array.shape)

    # Save the combined array into a new .mat file
    combined_data = {'all_features': combined_array} 
    scipy.io.savemat(output_file, combined_data)



In [26]:
# Example usage
file1_path = 'cover_1_4.mat'  
file2_path = 'cover_4_8.mat'  
file3_path = 'cover_8_10.mat'
output_file = 'cover_10k.mat'  # Specify the output file name



In [27]:
combine_mat_files(file1_path, file2_path,file3_path,output_file)

(1, 10000)


In [13]:
data=loadmat('cover_10k.mat')

In [14]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Tue Feb  6 20:50:13 2024',
 '__version__': '1.0',
 '__globals__': [],
 'all_features': array([[array([[0.13601132],
                [0.00848917],
                [0.00732037],
                ...,
                [0.00424021],
                [0.00215144],
                [0.00820888]], dtype=float32),
         array([[0.07701772],
                [0.01242618],
                [0.01433317],
                ...,
                [0.00467885],
                [0.00367624],
                [0.01374413]], dtype=float32),
         array([[0.1644316 ],
                [0.0078125 ],
                [0.00732037],
                ...,
                [0.00971279],
                [0.00570235],
                [0.00841775]], dtype=float32), ...,
         array([[0.0957185 ],
                [0.01033465],
                [0.01279528],
                ...,
                [0.00236031],
                [0.00196345],
                [0.00

In [29]:
data_temp=data["all_features"]

In [30]:
flat_temp = np.vstack([np.hstack(inner_array) for inner_array in data_temp])

In [31]:
flat_temp.shape

(48600, 10000)

In [32]:
flat_reshaped=flat_temp.transpose() 

In [33]:
pd.DataFrame(flat_reshaped)

0         1         2         3         4         5         6      \
0     0.136011  0.008489  0.007320  0.005598  0.005782  0.003937  0.001845   
1     0.077018  0.012426  0.014333  0.015502  0.012180  0.011934  0.011196   
2     0.164432  0.007812  0.007320  0.005782  0.005106  0.004060  0.004060   
3     0.057702  0.006582  0.005352  0.006951  0.006951  0.004552  0.003937   
4     0.091781  0.013103  0.013964  0.014149  0.015687  0.012549  0.010888   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.099286  0.011319  0.011380  0.012119  0.011934  0.008551  0.008059   
9996  0.164432  0.016425  0.018701  0.016548  0.015502  0.016609  0.011442   
9997  0.095719  0.010335  0.012795  0.012734  0.009289  0.007628  0.004737   
9998  0.086184  0.013041  0.012734  0.013410  0.011873  0.008428  0.005536   
9999  0.200357  0.008182  0.008243  0.006152  0.007136  0.008243  0.007382   

         7         8         9      ...     48590     48591     48592  \
0     0.001353  0.032788  0.007505  ...  0.001379  0.011384  0.002757   
1     0.007320  0.046321  0.011873  ...  0.001755  0.012909  0.003217   
2     0.003629  0.041708  0.007997  ...  0.001379  0.009525  0.004616   
3     0.004060  0.032050  0.005536  ...  0.002298  0.009316  0.002423   
4     0.009166  0.052719  0.012488  ...  0.007060  0.038872  0.010110   
...        ...       ...       ...  ...       ...       ...       ...   
9995  0.006152  0.040170  0.010458  ...  0.006642  0.031708  0.009880   
9996  0.010212  0.046444  0.017532  ...  0.000084  0.000272  0.000334   
9997  0.003999  0.020731  0.011996  ...  0.001399  0.005180  0.001734   
9998  0.003691  0.010150  0.012918  ...  0.002047  0.005932  0.003467   
9999  0.008674  0.182579  0.006582  ...  0.013201  0.083217  0.016919   

         48593     48594     48595     48596     48597     48598     48599  
0     0.004721  0.008877  0.022475  0.008292  0.004240  0.002151  0.008209  
1     0.004178  0.007185  0.008292  0.006517  0.004679  0.003676  0.013744  
2     0.009587  0.020533  0.030935  0.017838  0.009713  0.005702  0.008418  
3     0.003509  0.004992  0.010360  0.005473  0.003321  0.002360  0.011363  
4     0.014016  0.019655  0.024376  0.019843  0.014099  0.009943  0.040376  
...        ...       ...       ...       ...       ...       ...       ...  
9995  0.013452  0.015394  0.023039  0.016522  0.013097  0.008501  0.032522  
9996  0.001859  0.003384  0.004762  0.003196  0.001462  0.000564  0.000480  
9997  0.002465  0.005493  0.013786  0.004950  0.002360  0.001963  0.005681  
9998  0.005995  0.014057  0.020094  0.012762  0.006768  0.003593  0.007854  
9999  0.017191  0.019593  0.020533  0.020031  0.018527  0.017274  0.080292  

[10000 rows x 48600 columns]

In [2]:
stego=loadmat('stego_10k.mat')

In [4]:
stego_temp=stego['all_features']

In [6]:
flat_stego= np.vstack([np.hstack(inner_array) for inner_array in stego_temp])

In [9]:
flat_stego_trans=flat_stego.transpose()

In [15]:
df=pd.DataFrame(flat_stego_trans)

In [12]:
savemat('stego_10k_features',{'data':flat_stego_trans})

In [16]:
df.head()

0         1         2         3         4         5         6      \
0  0.134535  0.008305  0.007197  0.005906  0.006275  0.003875  0.001969   
1  0.077079  0.013164  0.014456  0.014764  0.012242  0.011626  0.011380   
2  0.164370  0.007936  0.007259  0.005598  0.005290  0.003875  0.004122   
3  0.057640  0.006459  0.005536  0.006705  0.007074  0.004552  0.004060   
4  0.091228  0.013103  0.013472  0.014333  0.016302  0.012365  0.010642   

      7         8         9      ...     48590     48591     48592     48593  \
0  0.001107  0.032480  0.007320  ...  0.001399  0.011342  0.002945  0.004700   
1  0.008182  0.046137  0.012180  ...  0.002068  0.012909  0.003133  0.004157   
2  0.003814  0.041400  0.008243  ...  0.001337  0.009525  0.004846  0.009441   
3  0.004183  0.032050  0.005721  ...  0.002277  0.009274  0.002444  0.003551   
4  0.009166  0.052473  0.012180  ...  0.007311  0.038768  0.010402  0.014078   

      48594     48595     48596     48597     48598     48599  
0  0.008689  0.022851  0.008042  0.004386  0.002172  0.008167  
1  0.007039  0.008815  0.006266  0.004637  0.003634  0.013702  
2  0.020198  0.031018  0.017859  0.009775  0.005661  0.008543  
3  0.004971  0.010277  0.005389  0.003572  0.002423  0.011342  
4  0.019363  0.025044  0.019258  0.014559  0.009671  0.039916  

[5 rows x 48600 columns]